compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
num_processes: 2          # 사용하고자 하는 GPU 수 (예: 2)
machine_rank: 0
num_machines: 1
main_process_ip: null
main_process_port: null
use_cpu: false
fp16: true               # fp16 사용 여부 (필요시)
deepspeed_config: {}      # DeepSpeed 미사용시 빈 객체로 설정